<?php

namespace Database\Seeders;

use Carbon\Carbon;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;

class BengkelSeeder extends Seeder
{
    
    public function run(): void
    {
        // Assuming bengkel owners have IDs 3 to 12 from UserSeeder
        DB::table('bengkel')->insert([
            [
                'id_user' => 3,
                'nama' => 'Bengkel Maju Jaya',
                'whatsapp' => '081234567890',
                'jenis_bengkel' => 'service',
                'foto_bengkel' => 'bengkel1.jpg',
                'alamat' => 'Jl. Sudirman No. 123, Jakarta',
                'jasa_penjemputan' => 'ada',
                'jam_buka' => '08:00:00',
                'jam_tutup' => '17:00:00',
                'hari_libur' => json_encode(['Minggu']),
                'latitude' => -6.200000,
                'longitude' => 106.816666,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id_user' => 4,
                'nama' => 'Bengkel Cepat Tambal',
                'whatsapp' => '081987654321',
                'jenis_bengkel' => 'tambal_ban',
                'foto_bengkel' => 'bengkel2.jpg',
                'alamat' => 'Jl. Thamrin No. 45, Jakarta',
                'jasa_penjemputan' => 'tidak',
                'jam_buka' => '07:00:00',
                'jam_tutup' => '18:00:00',
                'hari_libur' => json_encode(['Sabtu', 'Minggu']),
                'latitude' => -6.195000,
                'longitude' => 106.822500,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id_user' => 5,
                'nama' => 'Bengkel Motor Sejahtera',
                'whatsapp' => '081345678901',
                'jenis_bengkel' => 'service',
                'foto_bengkel' => 'bengkel3.jpg',
                'alamat' => 'Jl. Gatot Subroto No. 78, Jakarta',
                'jasa_penjemputan' => 'ada',
                'jam_buka' => '08:30:00',
                'jam_tutup' => '18:30:00',
                'hari_libur' => json_encode(['Minggu']),
                'latitude' => -6.210000,
                'longitude' => 106.820000,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id_user' => 6,
                'nama' => 'Bengkel Ban Murah',
                'whatsapp' => '081456789012',
                'jenis_bengkel' => 'tambal_ban',
                'foto_bengkel' => 'bengkel4.jpg',
                'alamat' => 'Jl. Kebon Jeruk No. 56, Jakarta',
                'jasa_penjemputan' => 'tidak',
                'jam_buka' => '06:30:00',
                'jam_tutup' => '19:00:00',
                'hari_libur' => json_encode(['Senin']),
                'latitude' => -6.205000,
                'longitude' => 106.815000,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id_user' => 7,
                'nama' => 'Bengkel Servis Cepat',
                'whatsapp' => '081567890123',
                'jenis_bengkel' => 'service',
                'foto_bengkel' => 'bengkel5.jpg',
                'alamat' => 'Jl. Hayam Wuruk No. 33, Jakarta',
                'jasa_penjemputan' => 'ada',
                'jam_buka' => '07:30:00',
                'jam_tutup' => '17:30:00',
                'hari_libur' => json_encode(['Sabtu', 'Minggu']),
                'latitude' => -6.190000,
                'longitude' => 106.830000,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id_user' => 8,
                'nama' => 'Bengkel Ban Jaya',
                'whatsapp' => '081678901234',
                'jenis_bengkel' => 'tambal_ban',
                'foto_bengkel' => 'bengkel6.jpg',
                'alamat' => 'Jl. Pangeran Jayakarta No. 22, Jakarta',
                'jasa_penjemputan' => 'tidak',
                'jam_buka' => '08:00:00',
                'jam_tutup' => '18:00:00',
                'hari_libur' => json_encode(['Minggu']),
                'latitude' => -6.185000,
                'longitude' => 106.825000,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id_user' => 9,
                'nama' => 'Bengkel Motor Prima',
                'whatsapp' => '081789012345',
                'jenis_bengkel' => 'service',
                'foto_bengkel' => 'bengkel7.jpg',
                'alamat' => 'Jl. Mangga Besar No. 67, Jakarta',
                'jasa_penjemputan' => 'ada',
                'jam_buka' => '07:00:00',
                'jam_tutup' => '19:00:00',
                'hari_libur' => json_encode(['Jumat']),
                'latitude' => -6.197500,
                'longitude' => 106.827500,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id_user' => 10,
                'nama' => 'Bengkel Jaya Abadi',
                'whatsapp' => '081890123456',
                'jenis_bengkel' => 'service',
                'foto_bengkel' => 'bengkel8.jpg',
                'alamat' => 'Jl. Cikini Raya No. 89, Jakarta',
                'jasa_penjemputan' => 'ada',
                'jam_buka' => '08:00:00',
                'jam_tutup' => '18:00:00',
                'hari_libur' => json_encode(['Minggu']),
                'latitude' => -6.192000,
                'longitude' => 106.840000,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id_user' => 11,
                'nama' => 'Bengkel Ban Prima',
                'whatsapp' => '081901234567',
                'jenis_bengkel' => 'tambal_ban',
                'foto_bengkel' => 'bengkel9.jpg',
                'alamat' => 'Jl. Kramat Raya No. 12, Jakarta',
                'jasa_penjemputan' => 'tidak',
                'jam_buka' => '07:30:00',
                'jam_tutup' => '17:30:00',
                'hari_libur' => json_encode(['Senin', 'Minggu']),
                'latitude' => -6.187500,
                'longitude' => 106.835000,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id_user' => 12,
                'nama' => 'Bengkel Motor Mandiri',
                'whatsapp' => '081012345678',
                'jenis_bengkel' => 'service',
                'foto_bengkel' => 'bengkel10.jpg',
                'alamat' => 'Jl. Senen Raya No. 45, Jakarta',
                'jasa_penjemputan' => 'ada',
                'jam_buka' => '08:00:00',
                'jam_tutup' => '18:30:00',
                'hari_libur' => json_encode(['Sabtu']),
                'latitude' => -6.180000,
                'longitude' => 106.845000,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
        ]);
    }
}

