<?php

namespace Database\Seeders;

use Carbon\Carbon;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;

class BengkelSeeder extends Seeder
{
    public function run()
    {
        // Bengkel owners have IDs 9 to 18 from UserSeeder
        DB::table('bengkel')->insert([
            [
                'id' => 1,
                'id_user' => 9,
                'nama' => 'Margora Motor',
                'whatsapp' => '081234567890',
                'jenis_bengkel' => 'service',
                'foto_bengkel' => 'margora.jpeg',
                'alamat' => 'Jl. Ahmad Yani No. 123, Banjarmasin',
                'jasa_penjemputan' => 'ada',
                'jam_buka' => '08:00:00',
                'jam_tutup' => '17:00:00',
                'hari_libur' => json_encode(['Minggu']),
                'latitude' => -3.325000,
                'longitude' => 114.590556,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => 2,
                'id_user' => 10,
                'nama' => 'Cahaya Maju Motor',
                'whatsapp' => '081987654321',
                'jenis_bengkel' => 'service',
                'foto_bengkel' => 'cahayamaju.jpeg',
                'alamat' => 'Jl. Lambung Mangkurat No. 45, Banjarmasin',
                'jasa_penjemputan' => 'ada',
                'jam_buka' => '07:30:00',
                'jam_tutup' => '18:00:00',
                'hari_libur' => json_encode(['Minggu']),
                'latitude' => -3.320000,
                'longitude' => 114.585000,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => 3,
                'id_user' => 11,
                'nama' => 'Apeng Motor',
                'whatsapp' => '081345678901',
                'jenis_bengkel' => 'service',
                'foto_bengkel' => 'apeng.jpeg',
                'alamat' => 'Jl. Veteran No. 78, Banjarmasin',
                'jasa_penjemputan' => 'tidak',
                'jam_buka' => '08:00:00',
                'jam_tutup' => '17:30:00',
                'hari_libur' => json_encode(['Sabtu', 'Minggu']),
                'latitude' => -3.315000,
                'longitude' => 114.595000,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => 4,
                'id_user' => 12,
                'nama' => 'Motor Star',
                'whatsapp' => '081456789012',
                'jenis_bengkel' => 'service',
                'foto_bengkel' => 'motorstar.jpeg',
                'alamat' => 'Jl. Pangeran Antasari No. 56, Banjarmasin',
                'jasa_penjemputan' => 'ada',
                'jam_buka' => '07:00:00',
                'jam_tutup' => '18:30:00',
                'hari_libur' => json_encode(['Minggu']),
                'latitude' => -3.310000,
                'longitude' => 114.600000,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => 5,
                'id_user' => 13,
                'nama' => 'Racing Boy',
                'whatsapp' => '081567890123',
                'jenis_bengkel' => 'service',
                'foto_bengkel' => 'racing.jpeg',
                'alamat' => 'Jl. Brigjen H. Hasan Basri No. 33, Banjarmasin',
                'jasa_penjemputan' => 'ada',
                'jam_buka' => '08:30:00',
                'jam_tutup' => '19:00:00',
                'hari_libur' => json_encode(['Jumat']),
                'latitude' => -3.305000,
                'longitude' => 114.605000,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => 6,
                'id_user' => 14,
                'nama' => 'Aulia Motor',
                'whatsapp' => '081678901234',
                'jenis_bengkel' => 'tambal_ban',
                'foto_bengkel' => 'AuliaMotor2.jpg',
                'alamat' => 'Jl. Kayu Tangi No. 22, Banjarmasin',
                'jasa_penjemputan' => 'tidak',
                'jam_buka' => '06:30:00',
                'jam_tutup' => '19:00:00',
                'hari_libur' => json_encode(['Minggu']),
                'latitude' => -3.330000,
                'longitude' => 114.580000,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => 7,
                'id_user' => 15,
                'nama' => 'Berkat Ban Motor',
                'whatsapp' => '081789012345',
                'jenis_bengkel' => 'tambal_ban',
                'foto_bengkel' => 'BerkatBanMotor.jpg',
                'alamat' => 'Jl. Pekapuran Raya No. 67, Banjarmasin',
                'jasa_penjemputan' => 'ada',
                'jam_buka' => '07:00:00',
                'jam_tutup' => '18:00:00',
                'hari_libur' => json_encode(['Senin']),
                'latitude' => -3.335000,
                'longitude' => 114.575000,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => 8,
                'id_user' => 16,
                'nama' => 'Rowo Bonjol',
                'whatsapp' => '081890123456',
                'jenis_bengkel' => 'tambal_ban',
                'foto_bengkel' => 'RowoBonjol.jpg',
                'alamat' => 'Jl. Kelayan A No. 89, Banjarmasin',
                'jasa_penjemputan' => 'tidak',
                'jam_buka' => '07:30:00',
                'jam_tutup' => '17:30:00',
                'hari_libur' => json_encode(['Sabtu', 'Minggu']),
                'latitude' => -3.340000,
                'longitude' => 114.570000,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => 9,
                'id_user' => 17,
                'nama' => 'Askum',
                'whatsapp' => '081901234567',
                'jenis_bengkel' => 'tambal_ban',
                'foto_bengkel' => 'askum.jpeg',
                'alamat' => 'Jl. Sungai Jingah No. 12, Banjarmasin',
                'jasa_penjemputan' => 'ada',
                'jam_buka' => '08:00:00',
                'jam_tutup' => '18:30:00',
                'hari_libur' => json_encode(['Minggu']),
                'latitude' => -3.345000,
                'longitude' => 114.565000,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => 10,
                'id_user' => 18,
                'nama' => 'Peter Ban',
                'whatsapp' => '081012345678',
                'jenis_bengkel' => 'tambal_ban',
                'foto_bengkel' => 'PeterBan.jpg',
                'alamat' => 'Jl. Mistar Cokrokusumo No. 45, Banjarmasin',
                'jasa_penjemputan' => 'tidak',
                'jam_buka' => '06:00:00',
                'jam_tutup' => '19:30:00',
                'hari_libur' => json_encode(['Selasa']),
                'latitude' => -3.350000,
                'longitude' => 114.560000,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
        ]);
    }
}